export const GET_ARTISTS = 'GET_ARTISTS';
export const GET_ARTISTS_ALL = 'GET_ARTISTS_ALL';
export const GET_ARTIST_DETAILS = 'GET_ARTIST_DETAILS';
export const CLEAR_ARTIST_DETAILS = 'CLEAR_ARTIST_DETAILS';
export const ADD_ARTIST = 'ADD_ARTIST';